version: '0.1.0-{build}'

image:
  - Visual Studio 2017

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      CONAN_PROFILE: vs2017-x86
      VCVARSALL_CMD: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      VCVARSALL_ARCH: x86
      CPPSTD: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      CONAN_PROFILE: vs2017-x64
      VCVARSALL_CMD: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      VCVARSALL_ARCH: x64
      CPPSTD: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      CONAN_PROFILE: vs2017-x64
      VCVARSALL_CMD: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      VCVARSALL_ARCH: x64
      CPPSTD: 17

configuration: Release

branches:
  except:
    - master

install:
  - SET PATH=C:\Python37;%PATH%
  - cinst ninja -y
  - python ci/install-dmenv.py
  - .\dmenv.exe install

before_build:
  - call "%VCVARSALL_CMD%" %VCVARSALL_ARCH%

build_script:
  - SET CXX=cl.exe
  - .\dmenv.exe run -- python ci/run-ci.py build-and-test --profile %CONAN_PROFILE% --cppstd %CPPSTD%
