language: cpp

dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
            - python3
            - python3-venv
      env:
        - CONAN_PROFILE=gcc8
        - COMPILER=g++-8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - python3
            - python3-venv
            - g++-6
      env:
        - CONAN_PROFILE=gcc6
        - COMPILER=g++-6

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - python3
            - python3-venv
            - g++-7
      env:
        - CONAN_PROFILE=gcc7
        - COMPILER=g++-7

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - python3
            - python3-venv
      env:
        - CONAN_PROFILE=gcc5
        - COMPILER=g++

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - python3
            - python3-venv
      env:
        - CONAN_PROFILE=clang7
        - COMPILER=clang++

before_install:
  - export CXX=${COMPILER}
  - python3 ci/install-dmenv.py

install:
  - ./dmenv install

script:
  - ./dmenv run -- python ci/run-ci.py build-and-test --profile ${CONAN_PROFILE}
