language: cpp

dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
            - python3
            - python3-pip
            - python3-setuptools
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - python3
            - python3-pip
            - python3-setuptools
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip3 install --upgrade pip
  - pip3 install conan==1.14.3 --user
  - pip3 install path-py --user

script:
  - python3 ci/run-ci.py build-and-test
