name: CI

on: [push]

env:
  CONAN_VERSION: 1.21.0
  PATH_VERSION: 13.1.0

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        compiler: [clang-3.9, clang-4.0, clang-5.0, clang-6.0, g++-5, g++-6, g++-7, g++-8]

        include:
          - os: ubuntu-18.04
            compiler: g++-8
            env:
              CPPSTD: 17
          
    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install conan and path
      run: pip install conan==$CONAN_VERSION path==$PATH_VERSION --user
    - name: Install C++ compiler and build tools
      run: sudo apt install ${{ matrix.compiler }} ninja-build
    - name: Build and test
      run: python $GITHUB_WORKSPACE/ci/run-ci.py build-and-test --profile $GITHUB_WORKSPACE/ci/conan-profiles/${{ matrix.compiler }} --cppstd $CPPSTD
