name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Checkout repository
      uses: actions/checkout@v1

