name: CI

on: [push]

env:
  CONAN_VERSION: 1.21.0

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Install conan
      run: |
        pip install conan==$CONAN_VERSION --user
        sudo apt install clang-3.9
    - name: Checkout repository
      uses: actions/checkout@v1
