name: CI

on: [push]

env:
  CONAN_VERSION: 1.21.0
  PATH_VERSION: 13.1.0

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        compiler: [clang++-3.9, clang++-4.0, clang++-5.0, clang++-6.0, g++-5, g++-6, g++-7, g++-8]
    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install conan and path
      run: pip install conan==$CONAN_VERSION path==$PATH_VERSION --user
    - name: Install C++ compiler
      # Already the default compiler on ubuntu 18.04
      if: matrix.compiler != 'clang++-6.0'
      run: sudo apt-get install ${{ matrix.compiler }}
    - name: Install build tools
      run: sudo apt-get install ninja-build
    - name: Build and test
      run: CXX=${{ matrix.compiler }} python $GITHUB_WORKSPACE/ci/run-ci.py build-and-test --profile $GITHUB_WORKSPACE/ci/conan-profiles/${{ matrix.compiler }}
  build-linux-cxx17:
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install conan and path
      run: pip install conan==$CONAN_VERSION path==$PATH_VERSION --user
    - name: Install C++ compiler
      run: sudo apt-get install g++-8
    - name: Install build tools
      run: sudo apt-get install ninja-build
    - name: Build and test
      run: CXX=g++-8 python $GITHUB_WORKSPACE/ci/run-ci.py build-and-test --profile $GITHUB_WORKSPACE/ci/conan-profiles/g++-8 --cxx17
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Install conan and path
      run: pip install conan==$CONAN_VERSION path==$PATH_VERSION --user
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install build tools
      run: brew install ninja
    - name: Build and test
      run: python $GITHUB_WORKSPACE/ci/run-ci.py build-and-test --profile $GITHUB_WORKSPACE/ci/conan-profiles/macos10.15
