name: CI

on: [pull_request, push]

env:
  CONAN_VERSION: 1.21.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install conan
      run: pip install conan==$CONAN_VERSION --user
